### ISSUE TITLE
Reflection masks not being applied 

### ISSUE THREAD

**Issue by JeremiahJiangJ** [bennyguo/nerfren#8]
I created 4 reflection masks but it doesn't seem like the masks are doing anything during training as there are no reflected regions in the images in checkpoints/vis. I used photoshop to create the masks by selecting the mirror in the image and creating a fill layer from it. I also applied --with_mask and specified --num_masks 4. 

Is there something else I need to look out for?

**Comment by bennyguo** [comment]
Hi! How many training images did you use? Could you try to label more masks or raise `lambda_beta_mask` to see if it works?

**Comment by JeremiahJiangJ** [comment]
Thanks for the reply and suggestions! I used 20 training images.

**Comment by bennyguo** [comment]
20 seems a reasonable amount. By the way, remember **not** to label the mirror frame as part of the reflection mask. It’s a strong cue about the depth of the mirror and should not be forced as a reflection area.

**Comment by JeremiahJiangJ** [comment]
Ok noted!
